### ISSUE TITLE
Wrong enum value for TRuleMessageActionType

### ISSUE THREAD

**Issue by YKPAIHELIb** [ekmsystems/IceWarp.Net#13]
Found typo in enum below. `Accept` and `Delete` have the same value = 0.

```
 public enum TRuleMessageActionType
    {
        Accept = 0,
        Delete = 0,
        Reject = 2,
        Spam = 3,
        Quarantine = 4
    }
```

Could you please fix it and resubmit your NuGet package for this lib? **;-)**

**Comment by elizabeth-young** [comment]
I've fixed this and deployed a new version (1.0.4) to nuget :-)
